fastlane_version "2.28.3"

default_platform :ios

platform :ios do

    desc "Build Ad Hoc"
    lane :buildAdHoc do

        #match(type: "adhoc", readonly: true)

        cocoapods

        build_app(
            workspace: ENV["WORKSPACE"],
            scheme: ENV["SCHEME"],
            configuration: ENV["CONFIGURATION"],
            export_options: {
                method: "ad-hoc",
                provisioningProfiles: {
                    ENV["APP_IDENTIFIER"] => ENV["PROFILE_AD_HOC"]
                }
            }
        )
    end
    
    desc "Deploy to Firebase Distribution"
    lane :firebase do

        buildAdHoc

        # https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane
        # bundle exec fastlane add_plugin firebase_app_distribution
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            testers: ENV["FIREBASE_TESTERS"],
            groups: ENV["FIREBASE_TEST_GROUP"],
            ipa_path: lane_context[SharedValues::IPA_OUTPUT_PATH],
            release_notes_file: "fastlane/release_notes.txt",
            service_credentials_file: ENV["FIREBASE_DIST_SERVICE_ACCOUNT_FILE"]
        )
    end
    
    desc "Increment Build Number"
    lane :inc do
    
        increment_build_number({
          build_number: latest_testflight_build_number + 1
        })
        build
        commit_version_bump(
            message: "Fastlane Build Bump",
            force: true,
        )
        #push_to_git_remote
    end
end
